### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by gpottepalem** [carlosgsouza/gradle-console#2]
Hi carlosgsouza,
I just tried this plugin and it is very cool.
I followed Installation section of this document and it looks like the following line is missing in this section which I figured it out after trying few other things. Without this it runs into exception: Task 'console' not found in root project <project-name>

apply plugin: 'console'

when I added this to my build script, it worked like a charm.
So, it might be helpful to add this line in there.
Thanks,
Giri

**Comment by carlosgsouza** [comment]
@carlolf were you able to get it to work? I tested with Gradle 1.11 and it seems to be working fine.

**Comment by carlolf** [comment]
I'm sorry, it is more than a year since I tried the tool. As a didn't get an answer on my problem, I did forget it. Maybe I'll try it once more.
