### ISSUE TITLE
Used with 'war' plugin, gradle-console adds groovy-all jar to war

### ISSUE THREAD

**Issue by djKianoosh** [carlosgsouza/gradle-console#6]
Nice plugin!

One thing I noticed though, if you use this in conjunction with the 'war' plugin, when you build the war file, the groovy all jar is added to the war file.  I think it's because you have 

```compile localGroovy()``` in your build.grade, no?  
https://github.com/carlosgsouza/gradle-console/blob/master/plugin/build.gradle#L8

**Comment by carlosgsouza** [comment]
Thanks a lot for reporting the problem. The issue has been fixed in 1.1.
